# -*- coding: utf-8 -*-
"""파이게임 이미지의 중앙정렬

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11O70f30XN6RMmpUMDKA996wOEEtGNXho
"""

import pygame

# 1. 초기화 -> 변수 선언
pygame.init()
# 2. 게임 화면 설정 -> 크기 고정
size = [400, 650]
screen = pygame.display.set_mode(size)

title = "PyGameExam"
pygame.display.set_caption(title)

# 3. 게임 화면 내에서의 설정 -> 변수
clock = pygame.time.Clock()


white = (255, 255, 255)
color1 = (112, 103, 76)

hero = pygame.image.load("C:\\Users\\USER\\Pictures\\hero2.png").convert_alpha()
hero = pygame.transform.scale(hero, (80, 80))
hero_width, hero_height = hero.get_size()
hero_x = round(size[0] / 2) - hero_width/2
#하드코딩은 상황에 따라 변할수 없기에 인덱스로 값을 대체해주어야 한다
hero_y = size[1] - hero_height - 150
#y축에 - hero_height - 150(은 본인이 원하는 위치를 설정)
#을 한이유는 hero 이미지가 화면에 바로 아래에 붙어있기 때문에 그만큼 빼주어야 한다


# 4. 메인이벤트
system_exit = 0
while(system_exit == 0):
    #  4-1. FPS(Frame per Sec) 설정
    clock.tick(2)
    
    #  4-2. 입력(키보드, 마우스)의 감지
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            system_exit = 1
    #닫기 버튼을 눌러 무한 반복문을 빠져나올수 있다

    #  4-3. 입력, 시간에 따른 변화
 
    
    #  4-4. 전사작업(그리기)
    screen.fill(black)
    screen.blit(hero, (hero_x, hero_y))

    #  4-5. 업데이트
    pygame.display.flip()

# 5. 종료
pygame.quit()